version: '3.8'

services:
  
  customer-service:
    container_name: customer-service
    build: ./customer-service
    hostname: customer-service
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=customer
      - CUSTOMER_SERVICE_PORT= :50051
      - ACCOUNT_SERVICE_PORT= :50052
    depends_on:
      - postgres

  account-service:
    container_name: account-service
    build: ./account-service
    hostname: account-service
    ports:
      - "50052:50052"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=customer
      - CUSTOMER_SERVICE_PORT= :50051
      - ACCOUNT_SERVICE_PORT= :50052
    depends_on:
      - postgres

  gateway-service:
    container_name: gateway
    build: ./gateway-service
    hostname: gateway-service
    ports:
      - "8080:8080"
    environment:
      - CUSTOMER_SERVICE_PORT= :50051
      - ACCOUNT_SERVICE_PORT= :50052
    depends_on:
      - customer-service
      - account-service

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: customer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
